apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
# data values must be base64 encoded
# echo -n 'username' | base64
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
